### ISSUE TITLE
Find Loop Task Explenation

### ISSUE THREAD

**Issue by dcts** [das-jishu/algoexpert-data-structures-algorithms#5]
I found the explenation to the excercise "Find Loop" (5th excercise of LinkedLists) not very clear. So I made this graph, hope it might help someone:
![Bildschirmfoto vom 2022-04-07 01-38-59](https://user-images.githubusercontent.com/44790691/162091597-bb5ab267-e0a3-4162-90a3-043f6364991e.png)

**Comment by das-jishu** [comment]
Thanks for sharing this! I am sure it will help people to visualize. 😄
