### ISSUE TITLE
Questions please!

### ISSUE THREAD

**Issue by sndp-s** [das-jishu/algoexpert-data-structures-algorithms#6]
Hey can someone please provide the questions as well? or inform where to find the questions without an algoexpert subscription?

**Comment by das-jishu** [comment]
I doubt that you will find the questions anywhere without a subscription. They are very strict with their policies.

**Comment by sndp-s** [comment]
found, thanks.

**Comment by npasha001** [comment]
@Sandeep-Tech would you mind sharing the questions to me pls
